"""Cria planilha e dados fictícios de cobranças para testes locais."""

from __future__ import annotations

import hashlib
import json
import os
from datetime import date, datetime
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

BASE_DIR = Path(__file__).resolve().parent.parent
PLANILHA = BASE_DIR / "Relatorios" / "cobrancas_teste.xlsx"
load_dotenv(BASE_DIR / ".env")

COLUNAS = [
    "identificador", "fornecedor", "servico", "orgao", "unidade", "numero_fatura",
    "responsavel", "competencia", "data_emissao", "data_vencimento", "valor_original",
    "valor_pago", "valor_pendente", "valor_atraso", "status", "telefone_destinatario",
    "origem_planilha",
]

REGISTROS = [
    {
        "identificador": "TESTE-COBRANCA-001", "fornecedor": "CESAN", "servico": "Água e esgoto",
        "orgao": "SRA", "unidade": "Sede", "numero_fatura": "NF-TESTE-001", "responsavel": "Equipe Financeira",
        "competencia": "08/2026", "data_emissao": "2026-08-01", "data_vencimento": "2026-08-25",
        "valor_original": 1250.00, "valor_pago": 0.00, "valor_pendente": 1250.00, "valor_atraso": 0.00,
        "status": "PROXIMA_DO_VENCIMENTO", "telefone_destinatario": "+5527999990001",
    },
    {
        "identificador": "TESTE-COBRANCA-002", "fornecedor": "EDP", "servico": "Energia elétrica",
        "orgao": "SRT", "unidade": "Anexo", "numero_fatura": "NF-TESTE-002", "responsavel": "Equipe Financeira",
        "competencia": "08/2026", "data_emissao": "2026-08-03", "data_vencimento": "2026-08-18",
        "valor_original": 782.45, "valor_pago": 0.00, "valor_pendente": 782.45, "valor_atraso": 12.50,
        "status": "VENCIDA", "telefone_destinatario": "+5527999990002",
    },
    {
        "identificador": "TESTE-COBRANCA-003", "fornecedor": "VIVO", "servico": "Telefonia móvel",
        "orgao": "CGU", "unidade": "Unidade 01", "numero_fatura": "NF-TESTE-003", "responsavel": "Equipe Financeira",
        "competencia": "08/2026", "data_emissao": "2026-08-05", "data_vencimento": "2026-08-30",
        "valor_original": 340.90, "valor_pago": 100.00, "valor_pendente": 240.90, "valor_atraso": 0.00,
        "status": "PENDENTE", "telefone_destinatario": "+5527999990003",
    },
    {
        "identificador": "TESTE-COBRANCA-004", "fornecedor": "SERPRO", "servico": "Serviço de limpeza",
        "orgao": "SERPRO", "unidade": "Prédio principal", "numero_fatura": "NF-TESTE-004", "responsavel": "Equipe Financeira",
        "competencia": "07/2026", "data_emissao": "2026-07-05", "data_vencimento": "2026-07-20",
        "valor_original": 1980.00, "valor_pago": 1980.00, "valor_pendente": 0.00, "valor_atraso": 0.00,
        "status": "PAGA", "telefone_destinatario": "+5527999990004",
    },
    {
        "identificador": "TESTE-COBRANCA-005", "fornecedor": "PREVIEW", "servico": "Manutenção predial",
        "orgao": "AGU (PF)", "unidade": "Sede", "numero_fatura": "NF-TESTE-005", "responsavel": "Equipe Financeira",
        "competencia": "08/2026", "data_emissao": "2026-08-10", "data_vencimento": None,
        "valor_original": None, "valor_pago": None, "valor_pendente": None, "valor_atraso": 0.00,
        "status": "SEM_DATA_DE_VENCIMENTO", "telefone_destinatario": "+5527999990005",
    },
    {
        "identificador": "TESTE-COBRANCA-006", "fornecedor": "AJP", "servico": "Manutenção predial",
        "orgao": "SPU", "unidade": "Anexo", "numero_fatura": "NF-TESTE-006", "responsavel": "Equipe Financeira",
        "competencia": "08/2026", "data_emissao": "2026-08-08", "data_vencimento": "2026-08-28",
        "valor_original": 450.00, "valor_pago": 0.00, "valor_pendente": 450.00, "valor_atraso": 0.00,
        "status": "AGUARDANDO_REVISAO", "telefone_destinatario": "+5527999990006",
    },
]


def criar_planilha() -> None:
    PLANILHA.parent.mkdir(parents=True, exist_ok=True)
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Cobrancas"
    sheet.append(COLUNAS)
    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="404040")
    for registro in REGISTROS:
        sheet.append([registro.get(coluna) for coluna in COLUNAS])
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = sheet.dimensions
    for column in sheet.columns:
        letter = column[0].column_letter
        sheet.column_dimensions[letter].width = min(max(max(len(str(cell.value or "")) for cell in column) + 2, 14), 28)
    workbook.save(PLANILHA)


def criar_tabelas(connection: psycopg.Connection) -> None:
    connection.execute("""
        CREATE TABLE IF NOT EXISTS leituras_planilha (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            caminho_origem TEXT NOT NULL, aba TEXT, hash_origem TEXT NOT NULL,
            versao_origem TEXT, lida_em TEXT NOT NULL, status TEXT NOT NULL,
            erro TEXT, UNIQUE(caminho_origem, hash_origem, aba)
        )
    """)
    connection.execute("""
        CREATE TABLE IF NOT EXISTS regras_cobranca (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL UNIQUE, descricao TEXT, ativa INTEGER NOT NULL DEFAULT 0,
            dias_antes_vencimento INTEGER NOT NULL DEFAULT 0, dias_depois_vencimento INTEGER NOT NULL DEFAULT 0,
            cobrar_vencidas INTEGER NOT NULL DEFAULT 0, cobrar_proximas INTEGER NOT NULL DEFAULT 0,
            valor_minimo DOUBLE PRECISION NOT NULL DEFAULT 0, servicos_json TEXT, fornecedores_json TEXT,
            orgaos_json TEXT, destinatarios_json TEXT, modelo_mensagem TEXT, exigir_aprovacao INTEGER NOT NULL DEFAULT 1,
            limite_diario INTEGER NOT NULL DEFAULT 0, intervalo_minimo_segundos INTEGER NOT NULL DEFAULT 0,
            horario_permitido TEXT, usuario_criador TEXT NOT NULL, criada_em TEXT DEFAULT CURRENT_TIMESTAMP,
            alterada_em TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    connection.execute("""
        CREATE TABLE IF NOT EXISTS destinatarios (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome TEXT NOT NULL, orgao TEXT, unidade TEXT, telefone TEXT, tipo TEXT NOT NULL,
            ativo INTEGER NOT NULL DEFAULT 1, autorizacao_registrada INTEGER NOT NULL DEFAULT 0,
            observacao TEXT, validado_em TEXT, criado_em TEXT DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    connection.execute("""
        CREATE TABLE IF NOT EXISTS contas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            identificador TEXT NOT NULL UNIQUE, fatura_id BIGINT, arquivo_origem TEXT,
            fornecedor TEXT, servico TEXT, orgao TEXT, unidade TEXT, numero_fatura TEXT,
            responsavel TEXT, competencia TEXT, data_emissao TEXT, data_vencimento TEXT,
            valor_original DOUBLE PRECISION, valor_pago DOUBLE PRECISION, valor_pendente DOUBLE PRECISION,
            valor_atraso DOUBLE PRECISION, status TEXT NOT NULL, telefone_destinatario TEXT,
            regra_cobranca_id BIGINT, origem_planilha TEXT, origem_hash TEXT, leitura_planilha_id BIGINT,
            atualizada_em TEXT DEFAULT CURRENT_TIMESTAMP, criada_em TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    connection.execute("CREATE INDEX IF NOT EXISTS idx_contas_teste_vencimento ON contas(data_vencimento)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_contas_teste_status ON contas(status)")


def inserir_dados(connection: psycopg.Connection) -> None:
    origem = str(PLANILHA)
    origem_hash = hashlib.sha256(PLANILHA.read_bytes()).hexdigest()
    leitura = connection.execute(
        """
        INSERT INTO leituras_planilha (caminho_origem, aba, hash_origem, versao_origem, lida_em, status)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (caminho_origem, hash_origem, aba) DO UPDATE SET lida_em = EXCLUDED.lida_em, status = EXCLUDED.status
        RETURNING id
        """, (origem, "Cobrancas", origem_hash, "teste-1.0", datetime.now().isoformat(timespec="seconds"), "sucesso")
    ).fetchone()[0]
    regra = connection.execute(
        """
        INSERT INTO regras_cobranca (nome, descricao, ativa, dias_antes_vencimento, cobrar_vencidas, cobrar_proximas,
            valor_minimo, exigir_aprovacao, usuario_criador)
        VALUES (%s, %s, 1, 5, 1, 1, 50, 1, %s)
        ON CONFLICT (nome) DO UPDATE SET alterada_em = CURRENT_TIMESTAMP
        RETURNING id
        """, ("TESTE-COBRANCA-REGRA", "Regra fictícia para testes de vencimentos", "teste")
    ).fetchone()[0]
    for registro in REGISTROS:
        connection.execute(
            """
            INSERT INTO contas (identificador, fornecedor, servico, orgao, unidade, numero_fatura, responsavel,
                competencia, data_emissao, data_vencimento, valor_original, valor_pago, valor_pendente, valor_atraso,
                status, telefone_destinatario, regra_cobranca_id, origem_planilha, origem_hash, leitura_planilha_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (identificador) DO UPDATE SET
                valor_pendente = EXCLUDED.valor_pendente, data_vencimento = EXCLUDED.data_vencimento,
                status = EXCLUDED.status, atualizada_em = CURRENT_TIMESTAMP
            """, tuple(registro.get(campo) for campo in COLUNAS[:-1]) + (regra, origem, origem_hash, leitura)
        )
    for registro in REGISTROS:
        connection.execute(
            """
            INSERT INTO destinatarios (nome, orgao, unidade, telefone, tipo, ativo, autorizacao_registrada, observacao)
            VALUES (%s, %s, %s, %s, 'email', 1, 1, %s)
            ON CONFLICT DO NOTHING
            """, (f"Destinatário {registro['orgao']}", registro["orgao"], registro["unidade"], registro["telefone_destinatario"], "Registro fictício de teste")
        )


def main() -> int:
    criar_planilha()
    database_url = os.environ["DATABASE_URL"]
    with psycopg.connect(database_url) as connection:
        with connection.transaction():
            criar_tabelas(connection)
            inserir_dados(connection)
    print(f"Planilha criada: {PLANILHA}")
    print(f"Registros de teste inseridos/atualizados: {len(REGISTROS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
