import os
import re
import sqlite3
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = str(BASE_DIR / "samf.db")
load_dotenv(BASE_DIR / ".env")


class _CompatRow(tuple):
    def __new__(cls, values, columns):
        row = super().__new__(cls, values)
        row.columns = tuple(columns)
        row.index = {name: position for position, name in enumerate(columns)}
        return row

    def __getitem__(self, key):
        if isinstance(key, str):
            return super().__getitem__(self.index[key])
        return super().__getitem__(key)

    def keys(self):
        return self.columns

    def items(self):
        return zip(self.columns, tuple.__iter__(self))


def _qmark_to_format(sql):
    converted = re.sub(r"\?(?=(?:[^']*'[^']*')*[^']*$)", "%s", sql)
    return re.sub(r"%(?![%sbt])", "%%", converted)


class _PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self._columns = []
        self._lastrowid = None

    def execute(self, sql, params=()):
        normalized = _normalize_postgres_sql(sql)
        insert = normalized.lstrip().upper().startswith("INSERT")
        if insert and "RETURNING" not in normalized.upper():
            normalized = normalized.rstrip().rstrip(";") + " RETURNING id"
        self._cursor.execute(_qmark_to_format(normalized), tuple(params or ()))
        self._columns = [item.name for item in (self._cursor.description or ())]
        if insert and self._columns:
            row = self._cursor.fetchone()
            self._lastrowid = row[0] if row else None
        return self

    def executemany(self, sql, params_seq):
        self._cursor.executemany(_qmark_to_format(_normalize_postgres_sql(sql)), params_seq)
        self._columns = [item.name for item in (self._cursor.description or ())]
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        return _CompatRow(row, self._columns) if row is not None else None

    def fetchall(self):
        return [_CompatRow(row, self._columns) for row in self._cursor.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def lastrowid(self):
        return self._lastrowid

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class _PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def execute(self, sql, params=()):
        cursor = _PostgresCursor(self._connection.cursor())
        return cursor.execute(sql, params)

    def cursor(self):
        return _PostgresCursor(self._connection.cursor())

    def commit(self):
        return self._connection.commit()

    def rollback(self):
        return self._connection.rollback()

    def close(self):
        return self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def _normalize_postgres_sql(sql):
    text = sql.strip()
    if text.upper().startswith("PRAGMA"):
        return "SELECT 1"
    if text.upper().startswith("CREATE TRIGGER"):
        return "SELECT 1"
    if "FROM SQLITE_MASTER" in text.upper():
        match = re.search(r"name\s*=\s*'([^']+)'", text, flags=re.IGNORECASE)
        table_name = (match.group(1) if match else "").replace("'", "''")
        return f"SELECT 1 WHERE to_regclass('{table_name}') IS NOT NULL"
    text = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        text,
        flags=re.IGNORECASE,
    )
    text = text.replace("INSERT OR IGNORE", "INSERT")
    if "INSERT OR IGNORE" not in sql.upper() and "ON CONFLICT" not in text.upper():
        return text
    if text.upper().startswith("INSERT") and "ON CONFLICT" not in text.upper():
        return text.rstrip(";") + " ON CONFLICT DO NOTHING"
    return text


def get_connection():
    """Retorna conexão SQLite ou PostgreSQL conforme DB_PROVIDER."""
    provider = os.getenv("DB_PROVIDER", "sqlite").strip().lower()
    if provider in {"postgres", "postgresql"}:
        import psycopg
        connection = psycopg.connect(os.environ["DATABASE_URL"], connect_timeout=10)
        return _PostgresConnection(connection)
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA busy_timeout = 10000")
    conn.row_factory = sqlite3.Row
    return conn

if __name__ == "__main__":
    try:
        conn = get_connection()
        print(f"--- SUCESSO ---")
        print(f"Conectado ao arquivo correto: {DB_PATH}")
        conn.close()
    except Exception as e:
        print(f"Erro ao conectar ao SQLite: {e}")
