"""Migra integralmente o SQLite real do SAMF para PostgreSQL.

A origem nunca e alterada. O destino deve estar vazio; o script aborta se
qualquer tabela de destino ja possuir registros.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg import sql

BASE_DIR = Path(__file__).resolve().parent.parent
SQLITE_PATH = BASE_DIR / "samf.db"
load_dotenv(BASE_DIR / ".env")


def quote(name: str) -> sql.Identifier:
    return sql.Identifier(name)


def sqlite_tables(connection: sqlite3.Connection) -> list[str]:
    return [
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]


def sqlite_columns(connection: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    return connection.execute(f'PRAGMA table_info("{table.replace(chr(34), chr(34) * 2)}")').fetchall()


def postgres_type(column: sqlite3.Row) -> str:
    declared = (column[2] or "TEXT").upper()
    if column[5] and declared == "INTEGER":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if declared in {"INTEGER", "INT", "BIGINT"}:
        return "BIGINT"
    if declared in {"REAL", "FLOAT", "DOUBLE"}:
        return "DOUBLE PRECISION"
    if declared in {"DATETIME", "TIMESTAMP"}:
        return "TIMESTAMP"
    if declared in {"DATE"}:
        return "DATE"
    if declared in {"BLOB", "BYTEA"}:
        return "BYTEA"
    return "TEXT"


def default_value(column: sqlite3.Row) -> str | None:
    value = column[4]
    if value is None:
        return None
    return value.replace("CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP")


def create_tables(sqlite_connection: sqlite3.Connection, postgres_connection: psycopg.Connection, tables: list[str]) -> None:
    for table in tables:
        columns = sqlite_columns(sqlite_connection, table)
        definitions = []
        for column in columns:
            definition = sql.SQL("{} {}").format(quote(column[1]), sql.SQL(postgres_type(column)))
            if column[3]:
                definition += sql.SQL(" NOT NULL")
            default = default_value(column)
            if default is not None:
                definition += sql.SQL(" DEFAULT ") + sql.SQL(default)
            if column[5] and postgres_type(column).startswith("BIGINT") is False:
                definition += sql.SQL(" PRIMARY KEY")
            elif column[5]:
                definition += sql.SQL(" PRIMARY KEY")
            definitions.append(definition)
        statement = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
            quote(table), sql.SQL(", ").join(definitions)
        )
        postgres_connection.execute(statement)


def sqlite_indexes(connection: sqlite3.Connection, table: str) -> list[tuple[str, bool, list[str]]]:
    result = []
    for row in connection.execute(f'PRAGMA index_list("{table.replace(chr(34), chr(34) * 2)}")').fetchall():
        name, unique = row[1], bool(row[2])
        columns = [item[2] for item in connection.execute(f'PRAGMA index_info("{name.replace(chr(34), chr(34) * 2)}")')]
        if columns and not name.startswith("sqlite_autoindex"):
            result.append((name, unique, columns))
    return result


def create_indexes(sqlite_connection: sqlite3.Connection, postgres_connection: psycopg.Connection, tables: list[str]) -> None:
    for table in tables:
        for name, unique, columns in sqlite_indexes(sqlite_connection, table):
            command = "CREATE UNIQUE INDEX IF NOT EXISTS" if unique else "CREATE INDEX IF NOT EXISTS"
            postgres_connection.execute(
                sql.SQL("{} {} ON {} ({})").format(
                    sql.SQL(command), quote(name), quote(table), sql.SQL(", ").join(quote(column) for column in columns)
                )
            )


def create_foreign_keys(sqlite_connection: sqlite3.Connection, postgres_connection: psycopg.Connection, tables: list[str]) -> None:
    for table in tables:
        for number, foreign in enumerate(sqlite_connection.execute(f'PRAGMA foreign_key_list("{table}")').fetchall(), 1):
            _, sequence, target_table, source_column, target_column, _, _, on_delete = foreign
            constraint_name = f"fk_{table}_{source_column}_{number}"
            statement = sql.SQL("ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}) ON DELETE {}")
            on_delete = {"NONE": "NO ACTION"}.get(on_delete.upper(), on_delete.upper())
            postgres_connection.execute(
                statement.format(
                    quote(table), quote(constraint_name), quote(source_column), quote(target_table), quote(target_column), sql.SQL(on_delete)
                )
            )


def create_audit_trigger(postgres_connection: psycopg.Connection) -> None:
    postgres_connection.execute(
        """
        CREATE OR REPLACE FUNCTION impedir_exclusao_auditoria_fn() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'Logs de auditoria não podem ser excluídos';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    postgres_connection.execute(
        """
        CREATE OR REPLACE TRIGGER impedir_exclusao_auditoria
        BEFORE DELETE ON auditoria_eventos
        FOR EACH ROW EXECUTE FUNCTION impedir_exclusao_auditoria_fn();
        """
    )


def migrate_data(sqlite_connection: sqlite3.Connection, postgres_connection: psycopg.Connection, tables: list[str]) -> dict[str, int]:
    counts = {}
    for table in tables:
        columns = sqlite_columns(sqlite_connection, table)
        names = [column[1] for column in columns]
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in names)
        statement = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            quote(table), sql.SQL(", ").join(quote(name) for name in names), placeholders
        )
        rows = sqlite_connection.execute(f'SELECT * FROM "{table.replace(chr(34), chr(34) * 2)}"').fetchall()
        for row in rows:
            postgres_connection.execute(statement, tuple(row))
        counts[table] = len(rows)
    return counts


def reset_sequences(postgres_connection: psycopg.Connection, tables: list[str]) -> None:
    for table in tables:
        postgres_connection.execute(
            """
            SELECT setval(pg_get_serial_sequence(%s, 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL)
            FROM """ + '"' + table.replace('"', '""') + '"',
            (table,),
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=str(SQLITE_PATH))
    parser.add_argument("--database-url", default=os.getenv("DATABASE_URL"))
    args = parser.parse_args()
    if not args.database_url:
        raise SystemExit("DATABASE_URL não configurada. Copie .env.example para .env e preencha a senha.")
    source = sqlite3.connect(args.source)
    source.row_factory = sqlite3.Row
    tables = sqlite_tables(source)
    with psycopg.connect(args.database_url) as target:
        existing = []
        for table in tables:
            if target.execute("SELECT to_regclass(%s)", (table,)).fetchone()[0] is not None:
                total = target.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(quote(table))).fetchone()[0]
                if total:
                    existing.append(f"{table} ({total})")
        if existing:
            raise SystemExit("Destino não está vazio: " + ", ".join(existing))
        with target.transaction():
            create_tables(source, target, tables)
            counts = migrate_data(source, target, tables)
            create_indexes(source, target, tables)
            create_foreign_keys(source, target, tables)
            if "auditoria_eventos" in tables:
                create_audit_trigger(target)
            reset_sequences(target, tables)
    source.close()
    print("Migração concluída sem alterar o SQLite.")
    for table, count in counts.items():
        print(f"{table}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
